name: Deploy to Railway

on:
  push:
    branches:
      - main  # Change this to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Get changed files in the commit range
      - name: Get changed files
        id: diff
        run: |
          echo "CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

      # Check if anything changed (always true on push, but explicit for clarity)
      - name: Check if any files changed
        id: any_check
        run: |
          if [ -n "$CHANGED" ]; then
            echo "deploy=true" >> $GITHUB_ENV
          else
            echo "deploy=false" >> $GITHUB_ENV
          fi

      - name: Deploy to Railway
        if: env.deploy == 'true'
        uses: railwayapp/railway-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          # Add your Railway project/service info here if needed
